version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wanted1234
      MYSQL_DATABASE: wanted_db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "sleep 20 && npm start"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
